add_newline = false

# Custom Format
format = """
$directory
$battery$jobs$username$hostname$memory_usage$git_branch$git_status$rust$cmake$cmd_duration$character"""

[cmd_duration]
min_time = 10000
format = "[$duration]($style) "

[hostname]
format = "on [$hostname](bold red) "

[directory]
truncation_symbol = ".../"
truncation_length = 5

[memory_usage]
disabled = false
threshold = 50

[git_branch]
format = "[$symbol$branch]($style) "

[jobs]
symbol = " "

[[battery.display]]
threshold = 30
