add_newline = false

# Custom Format
format = """
$username$hostname$directory
$battery$jobs$memory_usage$git_branch$git_status$rust$cmake$cmd_duration$character"""

[cmd_duration]
min_time = 10000
format = "[$duration]($style) "

[cmake]
format = "[$symbol($version)]($style) "
style = "bold cyan"

[hostname]
format = "@[$hostname](bold yellow):"

[directory]
truncation_symbol = ".../"
truncation_length = 5

[memory_usage]
disabled = true
threshold = 50

[git_branch]
format = "[$symbol$branch]($style) "

[jobs]
symbol = " "

[battery]
format = "[$symbol $percentage]($style) "

[[battery.display]]
threshold = 15
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[[battery.display]]
threshold = 50
style = "fg:#666666"

[username]
format = "[$user]($style)"
style_user = "bold green"
