add_newline = false

# Custom Format
format = """
$directory
$jobs$username$hostname$memory_usage$git_branch$git_status$rust$character$cmake"""


[hostname]
format = "on [$hostname](bold red) "

[directory]
truncation_symbol = ".../"
truncation_length = 5

[memory_usage]
disabled = false
threshold = 50

[git_branch]
format = "[$symbol$branch]($style) "

[jobs]
symbol = " "
