#! /bin/sh

sxhkd &
picom --experimental-backends --config .config/picom/picom.conf &
feh --bg-fill ~/background.jpg
polybar example &
optimus-manager-qt &
blueman-tray &
nm-applet &
redshift-gtk &
pasystray &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          20

bspc config focus_follows_pointer true

bspc config pointer_modifier shift

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

